spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
sql:
  init:
    mode: always