managment:
  endpionts:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  application:
    name: CrudService
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
logging:
  log4j2:
    logger:
      org:
        hibername: info
    config:
      override:
# Hibernate ddl auto (create, create-drop, validate, update)